info:
  app:
    name: Monitoring server
    description: Hystix - Circuit Breaker - Fault tolerance

server:
  port: 6161

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  cloud:
    inetutils:
      preferredNetworks: micro-starter_default

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
